apiVersion: batch/v1
kind: Job
metadata:
  name: areas-migrations-job
spec:
  template:
    metadata:
      labels:
        app: areas-migrations-pod
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z areas-mysql-svc 3306; do echo waiting for mysql; sleep 2; done;",
            ]
      containers:
        - name: areas-migrations-pod
          image: areas-migrations-image
          imagePullPolicy: Never
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "$(ASPNETCORE_ENVIRONMENT)"
            - name: "ConnectionStrings__ConnectionString"
              value: "Server=areas-mysql-svc;Database=$(DB_DATABASE);User=$(DB_USER);Password=$(DB_PASSWORD);Port=$(DB_PORT);"
          envFrom:
            - configMapRef:
                name: mysql-configmap
            - secretRef:
                name: mysql-secret
      restartPolicy: OnFailure
  backoffLimit: 4
