apiVersion: v1
kind: Service
metadata:
  name: areas-mysql-svc
  labels:
    app: areas-mysql-svc
spec:
  ports:
    - port: 3306
      name: areas-mysql
  clusterIP: None
  selector:
    app: areas-mysql-pod
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: areas-mysql-statefulset
spec:
  serviceName: areas-mysql-svc
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: areas-mysql-pod
  template:
    metadata:
      labels:
        app: areas-mysql-pod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: areas-mysql-pod
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: DB_DATABASE
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - name: areas-mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: areas-mysql-storage
          persistentVolumeClaim:
            claimName: areas-mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: areas-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
