{
 "title": "Dashboard Fiap TC Fase 3",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requisições por Minuto",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(app_requests_requests_total[1m])*60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de Resposta por Endpoint",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(app_request_duration_seconds_sum[5m])) \r\n/\r\nsum by (endpoint) (rate(app_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições por Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status_code) (app_requests_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilização de CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time_seconds_total[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumo de Memória (MB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Frequência de Coleta de Lixo",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(process_runtime_dotnet_gc_collections_count_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}