apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
spec:
  selector:
    app: rabbitmq-pod
  ports:
    - name: rabbitmq-port1
      port: 15672
      targetPort: 15672
      nodePort: 31572
    - name: rabbitmq-port2
      port: 5672
      targetPort: 5672
      nodePort: 31672
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-pod
  template:
    metadata:
      name: rabbitmq-pod
      labels:
        app: rabbitmq-pod
    spec:
      containers:
        - name: rabbitmq
          image: masstransit/rabbitmq
          ports:
            - containerPort: 15672
            - containerPort: 5672
