apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  DB_DATABASE: "tc4_contatos_regionais"
  DB_PORT: "3306"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  RABBITMQ_HOST: "rabbitmq-svc"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-configmap
data:
  POSTGRES_DB: "kong"
  KONG_DATABASE: "postgres"
  KONG_PG_HOST: "kong-database-svc"
  KONG_PROXY_ACCESS_LOG: "/dev/stdout"
  KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
  KONG_PROXY_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_LISTEN: "0.0.0.0:8001"
