apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
stringData:
  DB_USER: "root"
  DB_PASSWORD: "123456"

---

apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
stringData:
  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASWORD: "admin"

---

apiVersion: v1
kind: Secret
metadata:
  name: kong-secret
stringData:
  POSTGRES_USER: "kong"
  POSTGRES_PASSWORD: "kong"