apiVersion: v1
kind: Service
metadata:
  name: kong-database-svc
  labels:
    app: kong-database-svc
spec:
  ports:
    - port: 5432
      name: kong-database
  clusterIP: None
  selector:
    app: kong-database-pod
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kong-database-statefulset
spec:
  serviceName: kong-database-svc
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: kong-database-pod
  template:
    metadata:
      labels:
        app: kong-database-pod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: kong-database-pod
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: kong-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kong-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: kong-configmap
                  key: POSTGRES_DB
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "kong", "-d", "kong"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - name: kong-database-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: kong-database-storage
          persistentVolumeClaim:
            claimName: kong-database-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
